### ISSUE TITLE
Does not work (likely the new update)

### ISSUE THREAD

**Issue by SheepCommander** [TheF1ng3r/powercord-lastmessage#1]
Console

![image](https://user-images.githubusercontent.com/66646514/148680475-362e8149-e505-4830-bce3-b17db6313b69.png)

**Comment by AdamTuraj** [comment]
I'm working on replicating the issue, thanks for pointing it out

**Comment by AdamTuraj** [comment]
@SheepCommander I was unable to find that issue while fixing the other issues. I will push this update and if the issue persists please comment back here saying it is still not working.

**Comment by SheepCommander** [comment]
@TheF1ng3r Every time I press the `DownArrow` key (which is what I have it set as) it sends another one of this error 

![image](https://user-images.githubusercontent.com/66646514/148701890-832a9310-80d6-4d5c-aac2-45eb10d47b78.png)

![image](https://user-images.githubusercontent.com/66646514/148701820-8f39e5df-9966-4d51-89b3-734735ec5919.png)

**Comment by SheepCommander** [comment]
```
VM1086 C:\Users\zachi\powercord\src\Powercord\plugins\powercord-lastmessage\index.js:69 Uncaught TypeError: this.settings.get(...).split is not a function
    at HTMLDocument.<anonymous> (VM1086 C:\Users\zachi\powercord\src\Powercord\plugins\powercord-lastmessage\index.js:69)
    at HTMLDocument.listener (VM88 C:\Users\zachi\powercord\src\preload.js:154)
(anonymous) @ VM1086 C:\Users\zachi\powercord\src\Powercord\plugins\powercord-lastmessage\index.js:69
listener @ VM88 C:\Users\zachi\powercord\src\preload.js:154
```

**Comment by AdamTuraj** [comment]
Are you on the latest version of powercord and the plugin? Also what os are you on?

**Comment by SheepCommander** [comment]
win11 and yeah latest version of powercord AFAIK, I unplugged deleted all files then redownloaded yesterday

**Comment by AdamTuraj** [comment]
@SheepCommander I made an update a few hours ago. Have you updated to that? If you have I will test the plugin on my windows computer.

**Comment by SheepCommander** [comment]
@TheF1ng3r used both the built-in updated and git pull to verify that this plugin is up to date, still seeing the uncaught TypeError thing

Oh hey holding/pressing `Ctrl` also causes the error (except it says VM1059 instead of VM1086 if that matters)

**Comment by AdamTuraj** [comment]
@SheepCommander was able to replicate the issue on my Windows computer. Seems to be a windows issue

**Comment by AdamTuraj** [comment]
@SheepCommander I was able to replicate and fix on my Windows device. If the issue persists please create another issue or contact me on Discord. Thanks for the help!

**Comment by SheepCommander** [comment]
@TheF1ng3r Sorry, now it sometimes catches and sometimes doesn't. I send `test`, and it logs that and DownArrow inserts `test` into my text, but then I send something else but it still inserts `test`

![image](https://user-images.githubusercontent.com/66646514/148723243-cd634fb6-0fb7-4ab0-a918-a6e090e1fbe0.png)

Not sure if image will help

**Comment by AdamTuraj** [comment]
@SheepCommander don't know how that is possible as it is not in my code:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/51931914/148769623-a20ad1c3-adab-4f76-82ca-37ca09999b78.png">

**Comment by SheepCommander** [comment]
Sorry, seems now this error shows up whenever I send a new message with or without your plugin

![image](https://user-images.githubusercontent.com/66646514/148862641-174defa8-a7d2-4457-91e1-feb124d0f589.png)

**Comment by AdamTuraj** [comment]
@SheepCommander All good, I did find an issue and will be releasing a patch today or tomorrow

**Comment by SheepCommander** [comment]
Ah interesting
