### ISSUE TITLE
[Enhancement] Exception to while holding `ctrl` or `alt` by default

### ISSUE THREAD

**Issue by SheepCommander** [TheF1ng3r/powercord-lastmessage#3]
Also setting to have it only insert when your message box is empty?

**Comment by AdamTuraj** [comment]
@SheepCommander don't exactly know what you mean by the title but I added that second feature in the latest patch! This commit to be precise 474df8006c76cae613bd15ddffc40fcc6c954a3e

**Comment by SheepCommander** [comment]
@TheF1ng3r Nice! As for the title I meant "Dont do last-message thing while holding ctrl or alt"

**Comment by SheepCommander** [comment]
Oh it appears to already be an exception! Perhaps my earlier issue was actually caused by canary (it's now works 100% perfectly now that I've uninstalled and reinstalled canary)
