### ISSUE TITLE
Can you fix last message activating while editing a message?

### ISSUE THREAD

**Issue by SheepCommander** [TheF1ng3r/powercord-lastmessage#5]
![image](https://user-images.githubusercontent.com/66646514/149658880-b9d5be1d-af92-45cf-88e4-2b47c5c66220.png)
![image](https://user-images.githubusercontent.com/66646514/149658882-87d1111c-af56-4738-b779-90e619e6b067.png)

**Comment by AdamTuraj** [comment]
Didn't test for that. Thanks I will check it out

**Comment by AdamTuraj** [comment]
@SheepCommander it has been fixed. Thanks for another issue!

**Comment by SheepCommander** [comment]
Thanks! I highly doubt there will be any more issues lol
